### ISSUE TITLE
help yields no details

### ISSUE THREAD

**Issue by kategorically** [juba/scatterD3#1]
This is more of  a comment than a bug report. 

So far, the only available thing in the the help section (`help("scatterD3")`) is a list of arguments. Could use a bit more details - especially for arguments not used in the example.

Otherwise - awesome widget!

**Comment by juba** [comment]
Thanks !

Yes, you're perfectly right, the widget really lacks a minimal documentation besides the rare examples given. I think the ideal would be a vignette with a step-by-step widget construction, introducing settings along the way. I'll try to work on it soon.

**Comment by smach** [comment]
Note from an editor (we can't help ourselves):

help(package="scatterD3") documentation shows hello() as one of the available functions.

**Comment by juba** [comment]
@smach of course, I forgot to run `document()` and clean the documentation...

This should be fixed, thanks for taking the time to report it.

**Comment by juba** [comment]
I just added a vignette to the package. I also published it [online at Rpubs](http://rpubs.com/juba/scatterD3).

thanks for the feedback, and let me know if you find the documentation still not good enough.

**Comment by kategorically** [comment]
Looking good! Is there any way to specify the shapes when mapping them to `symbol_var`?

**Comment by juba** [comment]
No, not currently. Moreover, there are only six supported symbol types in d3 : 

https://github.com/mbostock/d3/wiki/SVG-Shapes#symbol_type

Feel free to open a new issue if you want to request it as a feature !
