### ISSUE TITLE
Great package 

### ISSUE THREAD

**Issue by ThoDuyNguyen** [juba/scatterD3#12]
Dear @juba 
I have just tested your package and found out that it really great. Below are just my thought (sorry for bad English) : 
- Have you put your library on http://www.buildingwidgets.com/ yet? I heavily use htmlwidgets on my dashboard and think that Shiny users check that site frequently for new htmlwidgets. 
- How do you think about make the syntax like "ggplot" and "dplyr", some thing like 

``` r
scatterD3(mtcars, x = wt, y = mpg, col = cyl, symbol = gear) %>% xlab("x axis") %>% ylab("y axis")
```

I have not developed htmlwidgets yet but i think I could dig into your code. 

Please let me know your thought about my thought.

 Kind regards

**Comment by juba** [comment]
Thanks ! I'm happy that you find this package useful.

I think the author of buildingwidgets.com did mention scatterD3 in [his latest post](http://www.buildingwidgets.com/blog/2015/10/8/week-40-networkd3-021-024).

For the syntax change you suggest, I think it would be quite a major change, and I'm not sure it would be that useful as scatterD3 doesn't intend to become a "generic" package as `ggplot2` or `dplyr` are. One thing that could be discussed, though, is that it could accept data from a data.frame instead of distinct vectors. In your example, it would become :

```
scatterD3(data = mtcars, x = wt, y = mpg, col_var = cyl, symbol_var = gear, xlab = "x axis", ylab = "y axis")
```

Not sure it wil be that useful, though...

**Comment by ThoDuyNguyen** [comment]
My bad, I have not noticed that it already mentioned on the new blog post. :+1:. A dedicated post is on the way, I think. 

For syntax, I notice that kind of implementation on recent htmlwidget packages (to make libraries coding style more consistent ?). 

P/S: 
On the readme.md, it should be install.packages("scatterD3") instead of install_packages("scatterD3") 
Kind regards

**Comment by juba** [comment]
Thanks for spotting the typo, I just fixed it.

For the syntax, I really love pipes and the code readability they provide, but here I can't see how it could apply : 
- `xlab`, etc. are really arguments, not functions. And you cannot specify them several times (you can't add several `col_var`, whereas you can add several `geom_line` in `ggplot2` for example).
- I don't think it could fit well with the code structure asked by `htmlwidget`.

But I may be wrong, and if you have examples of html widgets which use this syntax, it would be very interesting.

Thanks for your feedback.

**Comment by koundy** [comment]
Hi, I would lke to congratulate you on writing such a great package.
I want to save the plot in high resolution preferably in SVG to send it for publication. Can you kindly tell how I may do that?

**Comment by timelyportfolio** [comment]
@koundy, this is a fairly commonly request for all `htmlwidgets`, but unfortunately without an easy solution.  For now, if possible my recommendation is to use open in Chrome and use [svg-crowbar](https://nytimes.github.io/svg-crowbar/).  I tested and it works well with `scatterD3`.

I'm going to spend some time in November trying to iterate again through a solution.

**Comment by juba** [comment]
Another way is to wrap your scatterD3 call into a minimal shiny app that provides the "Export as SVG" scatterD3 feature. Something like this :

```
library(shiny)
shinyApp(ui=bootstrapPage(tags$a(id = "scatterD3-svg-export", 
                                 href = "#",
                                 class = "btn btn-default", "Download SVG"),
                          scatterD3Output("scatterPlot", height="700px")),
         server=function(input, output) {
           output$scatterPlot <- renderScatterD3({
             scatterD3(mtcars$wt, mtcars$mpg, lab = rownames(mtcars))})})
```

But it is far from ideal, and there currently is a bug with clip-path urls... (see Issue #13).

Like @timelyportfolio, I'd like to be able to provide something simpler soon...

**Comment by koundy** [comment]
Thank you. svg-crowbar is great ! transparency of the points is lost though :-(

**Comment by juba** [comment]
`clip-path` problems when exporting SVG should be fixed now.
