### ISSUE TITLE
add size and tooptip option

### ISSUE THREAD

**Issue by jpmarindiaz** [juba/scatterD3#14]
It would be awesome to specify the size of the points.
Also, the default tooltip uses a template to show all the variables called in the function.
It would be great to have a custom tooltip for each point and pass it as a variable.
Something like this:

```
scatterD3(x = mtcars$wt, y = mtcars$mpg, lab = rownames(mtcars),
       size = mtcars$gear, tooltip = paste(row.names(mtcars),paste0("has DRAT: ",mtcars$drat)),
          col_var=mtcars$cyl, symbol_var = mtcars$am,
          xlab = "Weight", ylab = "Mpg", col_lab = "Cylinders",
          symbol_lab = "Manual transmission")
```

Great package by the way!

**Comment by juba** [comment]
If I understand correctly, both are already possible : 
- If your point size is fixed, use the `point_size` argument. If it is variable, specify a vector of sizes as `size_var` argument.
- To specify custom tooltips, just generate a chracter vector and pass it to the `tooltip_text` argument.

Take a look at the [vignette](http://rpubs.com/juba/scatterD3) for more examples.

Note that size, colors, etc. can be changed and updated dynamically if your chart is integrated in a shiny app. See the [sample shiny app](http://data.nozav.org/app/scatterD3/)

**Comment by jpmarindiaz** [comment]
oops, sorry about that, should have checked the docs first!
Thanks.

**Comment by juba** [comment]
No problem ! Don't hesitate if you have any other question or feedback.
