### ISSUE TITLE
Inability to remove legend when fixed == TRUE

### ISSUE THREAD

**Issue by TimBock** [juba/scatterD3#16]
Hi, 

In the example below, I turn the legend off by setting legend_width to 0.

library(scatterD3)
x <- y <- 1:3
scatterD3(x, y, col_var = y, legend_width = 0)

However, when I fix the aspect ratio, the legend reappears if the plotting area has room for it.

It would be good if either legend_width = 0 set the legend to have a width of 0, or, if there was some other mechanism for turning the legend off.

Kind regards,
Tim

**Comment by juba** [comment]
Should be fixed in `master` : legend should no more be displayed when `legend_width = 0`.

Thanks for reporting !

**Comment by TimBock** [comment]
Thanks. ☺
