### ISSUE TITLE
xlim settings ignored when fixed = TRUE

### ISSUE THREAD

**Issue by TimBock** [juba/scatterD3#17]
For example, in the code below, a plot is created with xlim of 0 to 40, whereas the expected (by me) behavior is that I would end up with a "tall" plot, with a narrow x and high y dimension.

library(scatterD3)
scatterD3(x = mtcars$wt, y = mtcars$mpg, point_size = 15, point_opacity = 0.5, fixed = TRUE, xlim = c(0,10))

**Comment by juba** [comment]
Should be fixed now. If `xlim` or `ylim` are provided, they must be taken into account when `fixed = TRUE`. Note that if both are provided, only `ylim` is respected.
