### ISSUE TITLE
Underscores appearing instead of spaces in legend text

### ISSUE THREAD

**Issue by TimBock** [juba/scatterD3#18]
E.g., with the code below, the labels of the legend become Group_1 and Group_2:

library(scatterD3)
scatterD3(x = mtcars$wt, y = mtcars$mpg, point_size = 15, point_opacity = 0.5, fixed = TRUE,  col_var = rep(c("Group 1", "Group 2"), 16), col_lab = "Groups")

**Comment by juba** [comment]
That was to prevent special characters in CSS class names.

Should be fixed now, thanks for reporting.
