### ISSUE TITLE
Parameter for Dynamic Point Size

### ISSUE THREAD

**Issue by tinyheero** [juba/scatterD3#2]
Hi,

Is there a way to have dynamic point sizes? For instance, if I have a numeric column it would be great to be able to use those values to scale the point size. I see the point_size variable but that appears to be a global setting.

Thanks,

**Comment by juba** [comment]
Yes, for now on `point_size` is a fixed value. It should be possible to map it to a variable value.

**Comment by juba** [comment]
You now have the possibility to map the point sizes to a variable, via the `size_var`, `size_lab` and `size_range` arguments.
