### ISSUE TITLE
Customized tooltips text not showing up in Shiny App 

### ISSUE THREAD

**Issue by Cococatty** [juba/scatterD3#20]
Hi Juba

First my apologies!! I commented in the old issue page https://github.com/juba/scatterD3/issues/3 but not sure if it's still valid. So I submit another issue. Hope you don't mind if I'm not supposed to!

I have the similar issue with my Shiny app.
It works perfectly when I view it in VIewer, but it doesn't work when I run it in app.

Also I run the code from https://juba.shinyapps.io/scatterD3_shiny_app/ with few components commented out in server.R because it returns "unused variables". But the tooltips are not showing up either:

```
scatterD3(x = data()[,input$scatterD3_x],
          y = data()[,input$scatterD3_y],
          lab = rownames(data()),
          xlab = input$scatterD3_x,
          ylab = input$scatterD3_y,
          col_var = col_var,
          col_lab = input$scatterD3_col,
#              ellipses = input$scatterD3_ellipses,
          symbol_var = symbol_var,
          symbol_lab = input$scatterD3_symbol,
#               size_var = size_var,
#               size_lab = input$scatterD3_size,
#               key_var = rownames(data()),
          point_opacity = input$scatterD3_opacity
          , labels_size = input$scatterD3_labsize
#             , transitions = input$scatterD3_transitions
)
```

Below is the code that works fine in Viewer:

```
library(scatterD3)
tooltips <- paste("Territory Authority: ", test$AreaName,"</strong><br /> Percentage of x: "
                  , test$Percentage.x, "<br />"
                  , "Percentage of y: ", test$Percentage.y)
scatterD3(x = test$Percentage.x, y = test$Percentage.y
          , xlab = meandata$MeanName[meandata$MeanCode == unique(test$MeanCode.x)]
          , ylab = meandata$MeanName[meandata$MeanCode == unique(test$MeanCode.y)]
          , tooltip_text = tooltips
)
```

Below is part of my code for my Shiny app which doesn't show the tooltips :(

```
require("shiny") || install.packages("shiny")
require("DT") || install.packages("DT")
require("scatterD3") || install.packages("scatterD3")

library(scatterD3)

source("helper.R")


#Definte UI for the application
ui <- fluidPage(
  sidebarPanel(
    # The following part is groupCheckBox format for the travelMeans
    checkboxGroupInput(
      "travelMeans"
      , label = "Select the mean below:"
      , choices = meanChoices
      , selected = NULL
    )
  ),

  #Show the map
  mainPanel("Two-way Scatterplot", scatterD3Output("biScatter", width = "100%", height = "600px"))


#Definte server logic required to draw the map
server <- function(input, output, session) {
  biList <- reactive({
    # TO TEST, travelMeans = c('02','04')
    prepareTwoMeans(input$travelMeans)
  })

  output$biScatter <- renderScatterD3({
    tooltips <- paste("Territory Authority: ", biList$AreaName,"</strong><br /> Percentage of x: "
                      , biList$Percentage.x, "<br />"
                      , "Percentage of y: ", biList$Percentage.y)

    plot <- scatterD3(x = biList$Percentage.x, y = biList$Percentage.y
                      , xlab = meandata$MeanName[meandata$MeanCode == unique(biList$MeanCode.x)]
                      , ylab = meandata$MeanName[meandata$MeanCode == unique(biList$MeanCode.y)]
                      , tooltip_text = tooltips
    )
    return (plot)
  })

}

shinyApp(ui = ui, server = server)
```

I saw your comments above and tried to update my package in R. But not working.
Have I done something wrong?
Thank you very much!!

Carina

**Comment by juba** [comment]
Hi Carina,

First, to make the current `scatterD3_shiny_app` work, you'll have to install the latest development version of `scatterD3` from Github with : 

``` r
devtools::install_github("juba/scatterD3")
```

For the tooltips, I'm not sure if it is the cause of the problem, but in your server definition you should replace every `biList$foo` with `biList()$foo`. Here `biList`, created with a call to `reactive()` is in fact a reactive function which returns a `data.frame` each time one of the variables inside its definition changes. Plus, you are missing the opening `<strong>` tag in you tooltips text.

I tried your example with these changes and the tooltips did show correctly. Maybe  this will help ?

**Comment by Cococatty** [comment]
Hi Juba

Thank you soo much!! It works perfectly now!! I needed to install devtool but found some required components were missing, anyway, it's resolved now.

And the scatterD3 works so nice!! Thank you for writing such an amazing package!! :D :D

Carina

**Comment by juba** [comment]
Happy that the issue is fixed, and that you find the package useful :)
