### ISSUE TITLE
data argument (+ NSE?)

### ISSUE THREAD

**Issue by joelgombin** [juba/scatterD3#23]
Hi, 

great htmlwidget!

Do you think it would be possible to have an (optional?) data first argument, possibly with NSE eval of the x and y arguments, that would allow to use `scatterD3` jointly with pipes (`dplyr`-style). Something like:

``` r
data %>%
  scatterD3(x, y)
```

**Comment by joelgombin** [comment]
Although an easy solution that does not involve modifying `scatterD3`'s API is ti use the `%$%` operator in `magrittr`. The following actually works:

``` r
data %$%
  scatterD3(x, y)
```

**Comment by juba** [comment]
A `data` argument would definitely be useful, variables specification is too verbose. And integration with pipes would be great.

I'll try to look into it.

**Comment by juba** [comment]
I just added a `data` argument and NSE for `x`, `y`, `col_var`, `lab`... arguments. So you can do something like this : 

``` r
scatterD3(data = mtcars, x = wt, y = mpg)
```

The problem is, I can't make `data` the first argument, as it would break existing code... So that doesn't really solve your pipe question, even if you can do : 

``` t
mtcars %>% scatterD3(x = wt, y = mpg, data = .)
```
