### ISSUE TITLE
Three dimensional scatter plots?

### ISSUE THREAD

**Issue by MichelleKendall** [juba/scatterD3#25]
We've recently introduced `scatterD3` plotting into our R package [treescape](https://github.com/thibautjombart/treescape) (in the function `plotGrovesD3`) and it's been very enthusiastically received by users - it makes analysis so much quicker and easier. Thank you!

In our application (comparing phylogenetic trees via a distance metric and MDS plot) it's often useful to see a 3D scatter plot, too. At the moment in our Shiny app we're using `plot3d` from `rgl` which allows zooming and turning, but we've had requests for a 3D plot analogous to `scatterD3`, in particular with your legend hovering, tooltips and moveable labels. I wonder if this is on your "to do" list for the future? I don't know how complex this would be to code but if you could write something like this I know it would be hugely appreciated by treescape users. 

Many thanks,

Michelle

**Comment by juba** [comment]
Hi,

First, thanks for your feedback, I'm glad that `scatterD3` has been useful too you.

I'm not sure I could implement 3D scatterplots one day, It would be quite complex and I think it would require a different approach. But did you take a look at `rthreejs` ? It is an `htmlwidget` interface to `three.js`, and it seems it can be used to draw some 3D scatterplots via the `scatterplot3js` function : 

https://bwlewis.github.io/rthreejs/

https://github.com/bwlewis/rthreejs

**Comment by MichelleKendall** [comment]
Hi,

No problem, I suspected it might be quite complex! Yes thanks, `scatterplot3js` was my plan B. It doesn't quite have all the functionality and aesthetics I was hoping for but it's certainly a step nearer towards what we're after.

**Comment by timelyportfolio** [comment]
One other good option would be [plotly](https://plot.ly/r/).  Here are some [3d scatter examples](https://plot.ly/r/3d-scatter-plots/).

**Comment by MichelleKendall** [comment]
Great, thanks - I hadn't fully appreciated the scope of options available for 3d scatter plots in `plotly`. Thanks for bringing it to my attention.
