### ISSUE TITLE
scatterd3 colors not working

### ISSUE THREAD

**Issue by chewth** [juba/scatterD3#26]
The colors = hex is not working

**Comment by juba** [comment]
The following seems to work ?

``` r
scatterD3(x = mtcars$wt, y = mtcars$mpg, col_var = mtcars$cyl, 
              colors=c("#FF0000", "#00FF00", "#0000FF"))
```

Do you have a non-working example ?

**Comment by chewth** [comment]
Assuming we only want one color

scatterD3(x  =  mtcars$wt,y  =  mtcars$mpg,
               colors=c("#0000FF")) returns a blank plot

scatterD3(x  =  mtcars$wt,y  =  mtcars$mpg,
               colors="#0000FF") returns a blank plot

On 4/5/2016 3:01 AM, Julien Barnier wrote:

> The following seems to work ?
> 
> scatterD3(x  =  mtcars$wt,y  =  mtcars$mpg,col_var  =  mtcars$cyl,
>                colors=c("#FF0000","#00FF00","#0000FF"))
> 
> Do you have a non-working example ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/juba/scatterD3/issues/26#issuecomment-205449103

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by juba** [comment]
Ah, yes you're right, I never tried to give only one color to `colors` to change points color globally. Should be fixed now.

Thanks for the taking the time to report it.
