### ISSUE TITLE
Resize points after hovering

### ISSUE THREAD

**Issue by Nicolabo** [juba/scatterD3#27]
Hi,
It is possible to determine different size of points (than original size) when the user hovers a given point?

E.g. in ggvis there is an argument: size.hover.

**Comment by juba** [comment]
Hi,

This is not currently possible, but that's an interesting suggestion. I'll try to look into it.

Thanks !

**Comment by Nicolabo** [comment]
You're welcome. If I can suggest something more, I think fillOpacity.hover (e.g. default fillOpacity = 0.5 and fillOpacity.hover = 0.9 - is is really nice effect) is also interesting option in ggvis and I always use it.

**Comment by Nicolabo** [comment]
PS. Your package is awesome! Congrats:)

**Comment by juba** [comment]
This should now be possible with the `hover_size` and `hover_opacity` settings. See the vignette for an example.

Thanks for the suggestion !
