### ISSUE TITLE
Create own shape symbol - idea of implementing d3.map function

### ISSUE THREAD

**Issue by Nicolabo** [juba/scatterD3#28]
Your package is really awesome especially because it is based on pure d3.js. When it comes to use different shapes, d3's default values are: circle, square, diamonds, triangle-up, triangle-down and cross.
But sometimes there is a necessity to create own shape or group of shapes related to a given plot. In d3 it is quite easy task because you have to use [d3.map](https://github.com/mbostock/d3/blob/a10b22654c9275da1050e1513bbd834646c0bde3/src/svg/symbol.js#L49-L100) function. 
In R this task is probably impossible. You have to work on what R gives you. Therefore I was thinking it may be good idea to create in your package such function in which you can determine the svg path.

**Comment by juba** [comment]
Do you mean an R function which would transform a "shape" into an SVG path and pass it to d3 ? Could be useful, but seems quite complicated to do...

**Comment by Nicolabo** [comment]
Yeah, I imagine that. But I put it here as an idea, maybe some day...
