### ISSUE TITLE
continuous color scale

### ISSUE THREAD

**Issue by nFrechen** [juba/scatterD3#33]
I just discovered this wonderful package and am very happy to use it!

My question is: Is there a way to use a continuous color scale for floating point numbers? Or do I have to categorize them into bins (say 0 to 10, 10 to 20, 20 to 30 and so on)? Even if I do this, the sorting in the legend is not quite right for my purpose since the order will be for example 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9.

Maybe the package is just not made for using continuous color scales. Let me know!

**Comment by juba** [comment]
Hi,

You're right, continuous color scales are not currently supported, even if it would be a useful addition. And there's no way to specify a custom legend elements order, they are sorted alphabetically.

So for the moment I fear `scatterD3` will be a bit limited for continuous variables : you can map them to point size, but not to point color. I'll try to see if it could be implemented when I'll find some time.

**Comment by juba** [comment]
Continuous color scales should now be supported. If `col_var` is numeric, not a factor, and has more than 6 unique values, it is considered as continuous and drawn with the Viridis color scale. You can force a variable to be considered as continuous with `col_continuous = TRUE`.
