### ISSUE TITLE
 arguments `axes_font_size = ` and `legend_font_size = ` not implemented any more?

### ISSUE THREAD

**Issue by nFrechen** [juba/scatterD3#34]
The arguments `axes_font_size =` and `legend_font_size =` mentioned in the [introduction vignette](https://rawgit.com/juba/scatterD3/master/vignettes%2Fintroduction.html) do not seem to be implemented any more. At least I get the error `ERROR: unused argument (axes_font_size = "120%")` if I try to use them. Are there any new ways to influence the axes and legend font size?

**Comment by juba** [comment]
Are you using the CRAN version ? These arguments are only available in the Github version, if I'm right. You can install it with : 

``` r
devtools::install_github("juba/scatterD3")
```

**Comment by nFrechen** [comment]
You are right! I was using the CRAN version. The github version has the arguments.
