### ISSUE TITLE
Add links to points

### ISSUE THREAD

**Issue by juba** [juba/scatterD3#36]
Add the possibility to associate each point with a specific URL which can be open in a new tab when clicking on that point.

**Comment by tomliptrot** [comment]
That would be great. I love the package by the way.

**Comment by timelyportfolio** [comment]
I very much like the idea, but in general I find the context-switching with new pages very disruptive.  What I like better is `iframe`-link in a tooltip or separate area of the same page.

**Comment by juba** [comment]
@tomliptrot Thanks !

@timelyportfolio Yep, absolutely. I added this issue because someone requested it by mail, but I'm still not sure of the best way to implement it. Indded, opening a new tab or web page doesn't seem like optimal design and navigation...

**Comment by timelyportfolio** [comment]
but then I saw this https://twitter.com/sashaperigo/status/776116440843718656 and it works fairly well

**Comment by juba** [comment]
You mean, the combination of hover popup and new tab on click ?

Impressive visualisations...

**Comment by juba** [comment]
This should now be implemented with the new `url_var` argument. For example : 

``` r
mtcars$names <- rownames(mtcars)
mtcars$urls <- paste0("https://www.duckduckgo.com/?q=", rownames(mtcars))
scatterD3(data = mtcars, x = wt, y = mpg, lab = names, url_var = urls)
```

Note that this unfortunately won't work inside RStudio's internal browser.
