### ISSUE TITLE
1:1 line

### ISSUE THREAD

**Issue by ldecicco-USGS** [juba/scatterD3#38]
Sweet package!

Any chance there could be an enhancement to add specific horizontal, vertical, or a 1:1 line? A lot of times I'll have some important threshold, or expecting a 1:1 behavior.

**Comment by juba** [comment]
This should definitely be possible.

I'm currently in the middle of a rewrite to port `scatterD3` to d3v4, and it is taking (much) longer than expected, so new features are on hold for the moment. I can't promise any delay unfortunately, but I'll look into it.

Thanks for the suggestion.

**Comment by juba** [comment]
Hi,

I just implemented the possibility to add one or several custom lines to a scatterplot by passing a data frame to the `lines` argument. Everything should be explained in the visual guide : 

https://rawgit.com/juba/scatterD3/master/vignettes%2Fintroduction.html#adding-lines

This implementation may not be the easiest or the more intuitive, so any feedback is welcome !
