### ISSUE TITLE
I don't get interactive graphs

### ISSUE THREAD

**Issue by babelmansour** [juba/scatterD3#39]
Hello,

first your package is wonderful. It works very well, but when it opens in Firefox (I'm using Firefox) I don't have all the tools available in your sample. More precisely, I don't get the menu on the right which allow to choose variables, color them etc. I only have the reset zoom, export to svg and export label positions menu. Did I miss something? I used the devtools installation.
Thanks,

**Comment by juba** [comment]
You mean, you don't get the sidebar on the left as in this example ?

https://data.nozav.org/app/scatterD3/

That's perfectly normal. `scatterD3` by itself only manages the scatterplot, and its now integrated options menu (reset zoom, svg export, lasso...). The rest of the interface here is a shiny app, and you have to build it yourself to suit your needs. You can take a look at the sample shiny app source code as a starting point if you want : 

https://github.com/juba/scatterD3_shiny_app

**Comment by babelmansour** [comment]
Merci beaucoup. Je n’avais en effet pas compris cela ; je pensais en effet au menu de droite et non de gauche.
Bien cordialement,

Sébastien Dubois
Professeur associé/Associate Professor
Département Economie, Cultures & Affaires Internationales
Chercheur associé – Centre de Sociologie des Organisations, Sciences-Po
