### ISSUE TITLE
scatterD3 killing d3wordcloud

### ISSUE THREAD

**Issue by lrmelt** [juba/scatterD3#43]
I have added scatterD3 to my shiny app successfully, however it now kills any and all d3wordclouds that I have on the application. It even kills the d3wordclouds that are on other tabs and not concurrently active with the scatterD3.

By "kills" I mean that the d3wordcloud id is still there, just no SVG elements. All other d3 visualizations still work on the application.

Is this because the d3.min.js versions are different in both packages? Is there a way to declare which one to use?

**Comment by timelyportfolio** [comment]
My guess is related to https://github.com/fbreitwieser/sankeyD3/issues/4.  This transition from `d3v3` to `d3v4` is going to be painful.

**Comment by juba** [comment]
Thanks @timelyportfolio. Yes, this seems likely to be a d3v3-d3v4 conflict...

I don't really have any solution for this. The latest "stable" d3v3 scatterD3 version is 0.6.2, but it's a bit old and will miss some features : 

https://github.com/juba/scatterD3/releases/tag/0.6.2

And the latest commit with d3v3 should be this one : 

https://github.com/juba/scatterD3/tree/c789b0bc350f5af208f4817a66cd54f8f871ce77

**Comment by lrmelt** [comment]
I reverted back to that version and all works in Shiny but the tooltips...was there any known issue that you can remember?

The tooltips render appropriately in RStudio viewer...just not on the Shiny application as nothing appears on hover.

Thank you for the quick responses!

**Comment by juba** [comment]
Did you revert to 0.6.2 version, or the latest d3v3 commit ?

**Comment by lrmelt** [comment]
0.6.2

**Comment by juba** [comment]
Honestly, I don't remember... Is your shiny app or its source code accessible online ?

**Comment by lrmelt** [comment]
I just tried it with the latest d3v3 commit as well to no avail.

No, the app/code is not available. The best I can do is provide the snippets:

server.R
`output$bubblePlot <- renderScatterD3({ 
          tooltips <- paste("<strong>",Cluster$Category,"</strong><br/>X: ",Cluster$x,"<br/>Y: ",Cluster$y,"<br/>Frequency: ",Cluster$Frequency)
          scatterD3(x = Cluster$x, y = Cluster$y, lab = Cluster$Category,size_var = Cluster$Frequency,col_var=Cluster$Category,colors=ESI,legend_width = 0,size_range = c(200,2000),xlab = "X", ylab = "Y",tooltip_text = tooltips)
      })`
ui.R
`column(5,br(),
h4(style="text-align:center;","Category Cluster"),
scatterD3Output("bubblePlot",height = '500px'))`

**Comment by juba** [comment]
Any error in your javascript console in your browser ?

**Comment by lrmelt** [comment]
UPDATE...I just saw that the tooltip is rendering outside of the plot at the bottom corner of the page...let me mess around with my CSS to see if I am overwriting a tooltip position.

Stand-by.

**Comment by lrmelt** [comment]
It looks like the .scatterD3-tooltip is being adding to the DOM outside of the scatterD3 plot...so it is just snapping to the top position relative to itself which is way below the scatterD3 plot.

I added position:absolute to my styling and we are good to go.

Thank you for all the help!

**Comment by juba** [comment]
You're welcome ! I'm glad that you managed to fix it :)
