### ISSUE TITLE
Feature request: add plot title/subtitle

### ISSUE THREAD

**Issue by zhitkovk** [juba/scatterD3#48]
Hi,

I understand that I can go with the following scheme: "markdown section title then plot and then some text", but sometimes that is not a workaround.

Even if you won't add this feature I'd like to thank you for this package:) It's great!

**Comment by juba** [comment]
Thanks for your feedback and your suggestion.

It was not that easy to just add a title and subtitle on the plot, so I tried to implement it instead as a toggable caption : if you add a `caption` argument, an info sign icon will be added on the top right corner on your plot, and clicking on it will toggle the visibility of the caption. You can provide your caption either as a  single character string, or as a list with `tile`, `subtitle` and `text` elements.

You will find examples in the "visual guide" : 

https://rawgit.com/juba/scatterD3/master/vignettes%2Fintroduction.html#caption

I hope this will suit your needs !

**Comment by zhitkovk** [comment]
Thank you. I just had to be more attentive while reading the guide.

**Comment by juba** [comment]
Not at all ! I just implemented the feature based on your suggestion. It was not there last time you looked :-)

**Comment by zhitkovk** [comment]
Haha. The feature looks cool to my mind, not a direct subsitute of familiar title, yet you can provide a more complete description of what's happening on the plot.

**Comment by juba** [comment]
Yes, I understand it's not exactly what you asked, but adding a visible title to the plot would need a recomputation of all the plot dimensions, which is an already quite complex process...

**Comment by zhitkovk** [comment]
Maybe sometime in future :), for now I think caption covers most of the cases.
