### ISSUE TITLE
Keep centred focus for fixed axes

### ISSUE THREAD

**Issue by jon-nagra** [juba/scatterD3#49]
The plots with fixed axes not centred on the origin are displayed in the upper left corner.
If the variables xlim and ylim are fixed correctly this issue can be overridden, but, it requires a manual fix.
A piece of r code that illustrates the issue and the manual solution:

```
library(scatterD3)
xvar=cos(seq(0,2*pi,length.out=200))
yvar=2*sin(seq(0,2*pi,length.out=200))


scatterD3(x=xvar,y=yvar,fixed=TRUE)

move<-c(1,3)
xvar=xvar+move[1]
yvar=yvar+move[2]
# The ellipse is not centred
scatterD3(x=xvar,y=yvar,fixed=TRUE)


# fixing the issue manually 

# margin included so the points are not just at the border
margin=0.02

# calculate xlim and ylim
xmin=min(xvar)
xmax=max(xvar)
xd=xmax-xmin
xmin=xmin-xd*margin
xmax=xmax-xd*margin

ymin=min(yvar)
ymax=max(yvar)
yd=ymax-ymin
ymin=ymin-yd*margin
ymax=ymax+yd*margin

if(xd>yd){
    ymin=ymin-(xd-yd)/2
    ymax=ymax+(xd-yd)/2
}else{
    xmin=xmin-(yd-xd)/2
    xmax=xmax+(yd-xd)/2
}

scatterD3(x=xvar,y=yvar,
          xlim=c(xmin,xmax),
          ylim=c(ymin,ymax),
          fixed=TRUE)
  
```

**Comment by juba** [comment]
Hi, thanks for taking the time to open an issue. I'll take a look during the next days.

**Comment by juba** [comment]
I just pushed some commits that, I hope, will solve this issue. You can try them with the latest development version : 

    devtools::install_github("juba/scatterD3")

**Comment by jon-nagra** [comment]
The new version fixes the issue under both Linux and Windows OS. Thanks for your effort. 

P.S. If you ever need a hand at some project I will be glad to help; I do not have plenty of time, but, who has it?
I generally work with scripting languages (R, Python, Matlab) and I use html5, css (bootstrap) and LaTex (beamer) quite often for my presentations. I also have some knowledge of d3.js, still, I do not feel really comfortable in the dark worlds of Javascript and in a not so distant past I was a mathematician able to program in C and C++.
Thanks again.

**Comment by juba** [comment]
I'm glad the problem is fixe !

Thanks for your help proposition. Well, reporting issue is a welcomed contribution, don't hesitate to clone a project and submit a pull request if you add something useful. I'm far from a JavaScript myself, and my code could certainly be better and faster. But it's a good way to learn :-)

So, I don't have any precise help request right now, but don't hesitate to take a look at different projects, mine or others, and see if there are things that could be useful and fun to work on !
