### ISSUE TITLE
Floating scatterD3 

### ISSUE THREAD

**Issue by tinyheero** [juba/scatterD3#5]
Hi there,

Is there an easy way to float scatterD3 plots such that they are beside each other? The default output seems to place the scatterD3 plots into its own div element which ends up spanning the page. 

For instance, the R metricsgraphics htmlwidget has a functionality called `mjs_grid` which allows for placing the plots into a grid format (http://rpubs.com/hrbrmstr/mjs_grid_07). It would be great to be able to do the same with scatterD3 plots. 

Thanks,

**Comment by juba** [comment]
I don't think that creating a R grid function is necessary for this. `scatterD3` should be fully responsive, so you can use HTML markup and styling to place and size your widgets where you want.

For example, in a shiny app, you can use the shiny functions which generate the underlying markup, something like this : 

``` r
ui <- shinyUI(fluidPage(
  title="ScatterD3 Shiny Test",
    fluidRow(
      column(width=6, scatterD3Output("scatterD3.plot")),
      column(width=6, scatterD3Output("scatterD3.plot2"))
  )
))

server <- function(input, output) {
  output$scatterD3.plot <- renderScatterD3({
    scatterD3(x = mtcars$wt, y = mtcars$mpg)
  })
  output$scatterD3.plot2 <- renderScatterD3({
    scatterD3(x = rnorm(10), y = runif(10))
  })
}

shinyApp(ui, server)
```

**Comment by juba** [comment]
Closing it, I guess it worked ?
