### ISSUE TITLE
Single point in the bottom left corner

### ISSUE THREAD

**Issue by GiuseppeDiGuglielmo** [juba/scatterD3#53]
When a single point is plotted it is placed in the bottom left corner without any values on x and y axis. Something similar happens if all of the points have the same value for x or y, for example:
(10,21)
(10,43)
(10,64) 
are all on the leftmost border of the plot, or 
(10,21)
(13,21)
(16,21)
are all at the bottom of the plot.

Is it possible to center those point in the plot?

**Comment by juba** [comment]
You were absolutely right, thanks for taking the time to report the bug.

This should now be fixed in the Github version.
