### ISSUE TITLE
Feature request: size and color adjustment for axes titles

### ISSUE THREAD

**Issue by zhitkovk** [juba/scatterD3#54]
Sometimes you have really many points to display and it is hard to distinguish axis title. I suppose that suggested adjustments could help.

**Comment by juba** [comment]
There's already an option to increase the font size for the axes, but this changes both the axis title and the axis labels. I guess you would prefer to change only the axis title font size ?

I'm not sure I would add an axis title color argument though, as I'm trying to keep a balance between customisability and the number of arguments, which is already quite high...

**Comment by timelyportfolio** [comment]
Could also explore this [technique for custom styling](https://github.com/ramnathv/htmlwidgets/issues/231) or use `htmlwidgets::onRender` to add the JavaScript to customize.  Most of the CSS selectors can be found in the [`css`](https://github.com/juba/scatterD3/blob/master/inst/htmlwidgets/scatterD3.css).

**Comment by juba** [comment]
Thanks, very nice suggestions, I didn't even know about `prependContent` and `onRender`

Another direction I may take for `scatterD3` would be to implement a pipe-compatible syntax, which would keep the multiplicity of arguments readable and usable. Something like : 

    scatterD3(...) %>% add_lines(...) %>% theme(...)

I should take a look at other widgets to see how they do this, but this will not be before some weeks, I fear...

**Comment by timelyportfolio** [comment]
I'll try to come up with an example in the next couple of days to get the process started.  Thanks @juba for all you work!

**Comment by zhitkovk** [comment]
This time I really missed something in the docs. Thanks @timelyportfolio for the idea!

Pipelines are cool, but it is important to keep current simple syntax for options (I'm speaking about not very straightforward highcharts implementation with lists).
