### ISSUE TITLE
Overlapping points

### ISSUE THREAD

**Issue by GiuseppeDiGuglielmo** [juba/scatterD3#55]
This may be an enhancement. If two or more points are overlapping, then it should explode the view when the mouse is over the points.

**Comment by juba** [comment]
Well, this could be useful, but seems a bit complex to implement at first. In particular I would have to detect when the mouse is over several points in the same time, and I'm not sure how I could do that.

A partial workaround can be to use lasso selection to identify the points when they are overlapping, but I agree that it is not very convenient.
