### ISSUE TITLE
custom data <-> symbol mapping

### ISSUE THREAD

**Issue by GiuseppeDiGuglielmo** [juba/scatterD3#59]
Given a fixed custom data (e.g. an enum) it may be useful to map each element with a unique symbol.

**Comment by mmauri** [comment]
+1 to this
e.g. When assigning colors by a performance var, Assigning the red color, to a point with good performance is nonsense.
Same with symbol mapping , assigning the Symbol +, to a point that has bad performance is counter intuitive.
It would be great, that we could map symbols and colors to factors

BTW Awesome package, thanks for your work

**Comment by juba** [comment]
Custom symbol to value mapping should now be possible in the development version with the new `symbols` argument. You can use it as a vector of symbol names, or as a named vector whose names are data values and values are symbol names. Available symbol names are `"circle"`, `"cross"`, `"diamond"`, `"square"`, `"star"`, `"triangle"`, and `"wye"`.

Here is an example : 

```r
scatterD3(data = mtcars, x = wt, y = mpg, symbol_var = cyl,
          symbols = c("4" = "wye", "8" = "star", "6" = "triangle"))
```

Thanks for your patience and don't hesitate to give me your feedback on this.

**Comment by juba** [comment]
Custom value-symbol mapping should now be possible in the development version with the new `symbols` argument. You can pass a character vector of symbol names. If the vector is named then its names are use as original data value for the mapping.

Here is an example :

```r
scatterD3(data = mtcars, x = wt, y = mpg, symbol_var = cyl,
          symbols = c("4" = "wye", "8" = "star", "6" = "triangle"))
```

Available symbol names are : `"circle"`, `"cross"`, `"diamond"`, `"square"`, `"star"`, `"triangle"`, and `"wye"`.

Thanks for your suggestion, and I'd be happy to have your feedback on this.

**Comment by mmauri** [comment]
Thank you very much for your super fast answer! 
Will test it ASAP.

**Comment by mmauri** [comment]
Thank you very much for your super fast answer! 
Will test it ASAP.
