### ISSUE TITLE
Adding Custom Colors

### ISSUE THREAD

**Issue by tinyheero** [juba/scatterD3#6]
Hi,

Is there a way to specify a custom set of colors for scatterD3? Right now it seems to default to a set of standard colors from D3?

Thanks

**Comment by juba** [comment]
Just added a "colors" argument to specify a custom set of colors.

**Comment by tinyheero** [comment]
Thanks for this.

An enhancement might be to give a named color vector where the name of each element is associated with a value from the col_var. For example,

``` r
library("scatterD3")
library("magrittr")

gg_color_hue <- function(n) {
  hues = seq(15, 375, length=n+1)
  hcl(h=hues, l=65, c=100)[1:n]
}

plot.cols <- gg_color_hue(3)
plot.cols <- setNames(plot.cols, c("3", "4", "5"))

mtcars %$%
  scatterD3(x = wt, y = mpg, col_var = gear, colors = plot.cols)
```

This would link the 3, 4 and 5 gear values with a specific color to allow for more granularity. 

Right now, the colors appear to be assigned as a "first come first serve". In other words, `plot.cols[1]` gets assigned to 4, `plot.cols[2]` gets assigned to 3, `plot.cols[3]` gets assigned to 5 because `unique(mtcars[, "gear"])` has the order `4 3 5`. If the input character vector isn't named, then this would be a good default.

**Comment by juba** [comment]
I'll look into it and see if it does not add to much code complexity.

**Comment by timelyportfolio** [comment]
I can think of two other possibly useful color options.
- One additional way would be to pass a htmlwidgets::JS() function as the colors argument for the JavaScript literate users, but in the cases I have added I don't think it gets used much. As an example,

```
htmlwidgets::JS(
  sprintf(
    'd3.scale.ordinal().range([%s]).domain([%s])',
    paste0(unique(mtcars$cyl),collapse=","),
    paste0(blues9,collapse=",")
  )
)
```
- Supply the name of the column in the data that contains a color for the point.

```
mtcars$color <- scales::col_factor(
  "Set1", sort(unique(mtcars$cyl))
)(mtcars$cyl)

# and then supply color as `colors` arg
scatterD3( mtcars, ..., colors = "color")
# or RStudio leaflet, ggvis something like this
scatterD3( mtcars, ..., colors = ~color)
```

**Comment by tinyheero** [comment]
Thanks for this. It works perfectly!
