### ISSUE TITLE
How do I customize unit circle?

### ISSUE THREAD

**Issue by jamesthesnake** [juba/scatterD3#60]
I want to be able to : 
1. change its center of origin
2. change its radius ( I know its a "unit " circle but can we expand it)
3. show only half of it ( e.g the northern hemisphere)

Is there a way to do this or just draw curved lines in R

**Comment by juba** [comment]
Unfortunately, unit circle is  a utility feature right now, and it's not possible to customize it, and there's no plan to introduce this in the short term (though it would not be that hard to implement...).
