### ISSUE TITLE
remove the legend 

### ISSUE THREAD

**Issue by jamesthesnake** [juba/scatterD3#61]
Hey I'm trying to find a way just to remove the legend ( in the context of my implementation red and blue are very straightforward) since the legend takes up so much space and fits weirdly the windows I'm using the implementation for.

**Comment by jamesthesnake** [comment]
<img width="501" alt="screen shot 2017-01-17 at 11 55 33 am" src="https://cloud.githubusercontent.com/assets/8227820/22030543/e59df476-dcab-11e6-9247-67d884339630.png">
This is what it looks like and would rather have it not at all

**Comment by juba** [comment]
Surely you already guessed it, but for the record you can disable the legend completely with `legend_width = 0`.
