### ISSUE TITLE
Export labels positions for lasso selection subset only?

### ISSUE THREAD

**Issue by zhangz19** [juba/scatterD3#63]
I wonder if it is possible to do lasso selection for a subset and then export labels positions for this subset only? Currently it still export the full data set; Or somehow return the indices of lasso selected samples for subsequent operation which I guess would be helpful in addition to highlighting them.

**Comment by zhangz19** [comment]
One possible way: 
scatterD3(data = mtcars, x = wt, y = mpg, lab = names, lasso = TRUE, lasso_callback = "function(sel) {prompt('Copy to clipboard: Ctrl+C, Enter', sel.data().map(function(d) {return d.lab}).join(','));}")
to access the selected labels. 
Again directly exporting lasso selected subset to csv or automatic obtaining selected cases for subsequent analysis would be appreciated.

**Comment by juba** [comment]
`lasso_callback` is just an entry point for user-developed functions, and does not provide any functionality by itself. There's an example which is very close to your workaround in the package vignette : 

https://cran.r-project.org/web/packages/scatterD3/vignettes/introduction.html#lasso-selection-tool

If you use `scatterD3` with shiny there are ways to use dialogs or more complex features. You can see an example in my `explor` package, where lasso selection triggers a modal dialog with points ids, both as a list and as an R vector.

**Comment by aloboa** [comment]
No way to actually select the data instead of the label positions?

**Comment by juba** [comment]
What would you like to achieve exactly ?

**Comment by aloboa** [comment]
Simply select with lasso and save the subsetted dataframe.

**Comment by juba** [comment]
Not sure this would be possible with a JavaScript callback. Within a shiny app you should be able to get the selected points id and then subset your original data frame.
