### ISSUE TITLE
Integration with ioslides

### ISSUE THREAD

**Issue by ScottStetkiewicz** [juba/scatterD3#64]
I'm putting a ScatterD3 `shiny` app into an `ioslides` presentation. When I hover over an element in the legend, the relevant points are highlighted on the plot.  However, when I select the fullscreen option to make the slide fit the screen and attempt to do the same thing, the points on the plot are only highlighted for ~4 seconds before they disappear.   Here's a small example:

```
---
runtime: shiny
output: 
  ioslides_presentation:
    css: HMS_Test.css
---

```{r, echo=FALSE}
library(scatterD3)

ui <- fluidPage(
  fluidRow(
    column(4,
           wellPanel(
             selectInput("Living", "Choose Life", 
                         choices = c("Life", "Death"))
           )
    ),
    column(8,
           scatterD3Output("distPlot", height = "550px"))
  )
)

server <- function(input, output) {
  output$distPlot <- renderScatterD3({
    mtcars$names <- rownames(mtcars)
    scatterD3(data = mtcars, x = wt, y = mpg, lab = names,
              col_var = cyl, symbol_var = am,
              xlab = "Weight", ylab = "Mpg", col_lab = "Cylinders",
              symbol_lab = "Manual transmission")
  })
}
shinyApp(ui = ui, server = server)
```3 CLOSING BACKTICKS WON'T RENDER ALONE IN THIS POST  
```
Any thoughts on how to fix this?

**Comment by juba** [comment]
Hi Scott, and sorry for the delay of my answer.

I've tried your example, but fail to reproduce the bug. Where do you run your presentation ? In RStudio, in a browser ? What do you mean by "fullscreen option", is it ioslides related or just putting your browser to display fullscreen ?

And last, I'm missing your `HMS_test.css` file, I think, and I don't know if the issue may be related to it...

**Comment by ScottStetkiewicz** [comment]
I was running it through the browser - I'm embarrassed to say that I didn't think to try it in a different browser before posting here. The problem persists in Vivaldi, but works as expected using Chrome.  Sorry for the hassle!
