### ISSUE TITLE
click_callback

### ISSUE THREAD

**Issue by joelgombin** [juba/scatterD3#65]
For JS n00bs such as me, could you give a simple example of what the value of the `click_callback` argument might be? I'd like to open a new webpage when clicking on a point.
Thank!

**Comment by juba** [comment]
If all you want to do is open a page on click, you ca use the `url_var` argument, no need to create a callback : 

https://cran.rstudio.com/web/packages/scatterD3/vignettes/introduction.html#open-urls-when-clicking-points

There are also some callbacks examples in the vignette : 

https://cran.rstudio.com/web/packages/scatterD3/vignettes/introduction.html#javascript-callback-on-clicking-point

**Comment by joelgombin** [comment]
Right, my bad, I didn't see there was a vignette! Sorry!
