### ISSUE TITLE
scatterD3 and C3 clash?

### ISSUE THREAD

**Issue by Tixierae** [juba/scatterD3#67]
Thanks for the great package! 

The following **minimal reproducible example** works fine, but when I uncomment `scatterD3Output("scatterPlot", height = "700px")` it stops working: **no error is given, but no output is shown**.  When I right click and inspect the element then console gives: `TypeError: c.scale is undefined`

Do you know how to fix that? Or are the C3 and scatterD3 libraries just incompatible? Thanks much in advance for any help.

    library(shiny)
    library(C3)
    library(scatterD3)
    
    server = function(input, output) {
      my_df = reactive({
        input$button
        my_df = list(a=runif(1,0,100),b=runif(1,0,100),c=runif(1,0,100))
        list(my_df=my_df)
      })
      output$my_pie = renderC3Pie({
        C3Pie(value = my_df()$my_df)
      })
      output$scatterPlot <- renderScatterD3({
        scatterD3(x=1,y=1)
      })
    }
        
    ui = shinyUI(
      fluidPage(
        fluidRow(
          actionButton('button', "Draw!"),
          C3PieOutput('my_pie')
        ),
        fluidRow(
          br()#,scatterD3Output("scatterPlot", height = "700px")
        )
      )
    )
    shinyApp(ui = ui, server = server)

**Comment by Tixierae** [comment]
potentially related to https://github.com/juba/scatterD3/issues/43

**Comment by juba** [comment]
Unfortunately yes, as c3js seems to be based on d3v3 and scatterD3 on d3v4, this may cause problems.

Could you tell me what `C3` R package you're using exactly ?

**Comment by Tixierae** [comment]
Thanks for the quick reply. I'm using this `C3`: https://shiny.rstudio.com/articles/js-widget-functionality.html
You can install it via `devtools::install_github("FrissAnalytics/shinyJsTutorials/tutorials/materials2/C3")`

**Comment by Tixierae** [comment]
Do you think this could work?: https://stackoverflow.com/questions/44173693/using-different-d3-versions-on-same-html-page/44175745#44175745

**Comment by juba** [comment]
Yes, thanks for the pointer, this could be useful. I'll take a look into it, maybe tomorrow.

**Comment by juba** [comment]
Ok, I just pushed a fix to the development version. I used your stackoverflow link to rename every `d3` instance to `d3v4`. Could you please test if this works for you ?

Thanks !

**Comment by Tixierae** [comment]
It works as a charm! Thanks much!
