### ISSUE TITLE
Save as PDF?

### ISSUE THREAD

**Issue by romanhaa** [juba/scatterD3#69]
Would it be possible to add an option to save a plot as PDF instead of SVG? My fellow biologists are not very familiar with SVG ;)

**Comment by juba** [comment]
I'm not sure it will be possible unfortunately. The plot itself is generated in SVG, so it's quite simple to export it to a file. But converting it to PDF would be more complicated. 

In the meantime you can always open your SVG in Inkscape and convert it to PDF (or use another conversion tool). But I agree it is not as straightforward.

**Comment by romanhaa** [comment]
Thanks for the feedback! I'll close this as there is not much to add at this point :)
