### ISSUE TITLE
Export to SVG crashes with too much data?

### ISSUE THREAD

**Issue by romanhaa** [juba/scatterD3#70]
I still have to do some testing before I can say for sure that it is the size of data that causes the crash, but so far that is the only difference I know. To give some reference, when exporting a scatter plot with 10s of points I have now problem, when working with 10,000 - 20,000 however it simply crashes. I currently have no access to the error message but will look into this as soon as I can.

**Comment by juba** [comment]
Yes, unfortunately I'm not surprised, this package is not really suitable for scatter plots with thousands of points... Display and zooming will be slow, and SVG export may cause problem as it is done by passing a base64-encoded version of the SVG code.

It must however depend on your computer and on the browser you use when exporting. As an example I just tried with a 100,000 points scatterplot in the latest stable RStudio and it worked. Maybe if you can take a look at your JavaScript console when exporting to see if there is any error message ?
