### ISSUE TITLE
Order of groups in legend

### ISSUE THREAD

**Issue by romanhaa** [juba/scatterD3#71]
Hi Julien,

It's me again :) I was wondering if there is a way to prevent re-ordering of the groups in the legend? The variable is a factor but in the legend they are re-ordered alphabetically or, if numeric, as 1,10,11, etc.

![screen shot 2018-10-10 at 11 41 28](https://user-images.githubusercontent.com/18103560/46727846-b7b8f700-cc81-11e8-82f9-159526201691.png)

Thanks,
Roman

**Comment by juba** [comment]
Hi,

Yes, you're right, ideally the legend should follow the order of the labels when the source variable is a factor. Until now I'm applying a `sort` on the legend, I think it was to maintain consistency between plots (otherwise the values are shown depending on their order of appearance). I'll take a look to see if I can do it differently...

**Comment by romanhaa** [comment]
My data is actually quite well structured (the data frame is sorted) so I just removed the two `.sort()` calls for the legend. It works in my case but I guess in general it would be nice to carry over the order of levels from R. Perhaps I come up with a more consistent solution somewhen.

**Comment by juba** [comment]
Hi,

I just commited a fix on the development version, so that the levels order should be kept in the legend when `col_var` or `symbol_var` is a `factor`.

If you are able to test it when you can, I'll be happy to have your feedback.

Thanks !

**Comment by mmauri** [comment]
This is an issue, I also faced, 
I can confirm that with the dev version is working

Kudos!

**Comment by juba** [comment]
Great ! Thanks for taking the time to give your feedback.

**Comment by Tixierae** [comment]
That fixed the issue for me as well! Thanks much @juba!
