### ISSUE TITLE
Add label layout

### ISSUE THREAD

**Issue by juba** [juba/scatterD3#73]
For example : 

https://d3fc.io/api/label-layout-api.html

**Comment by baohongz** [comment]
http://tinker10.github.io/D3-Labeler/

**Comment by Tixierae** [comment]
just checking in - any progress on this?

**Comment by juba** [comment]
Unfortunately no, I didn't find time to work on this yet...

**Comment by Tixierae** [comment]
no prob, thanks for the update!

**Comment by juba** [comment]
I just commited a first try at automatic label positioning, using the d3-labeler plugin. You can try it by adding `labels_positions = "auto"` to your `scatterD3` call. Please consider it to be still experimental and subject to changes.

**Comment by Tixierae** [comment]
whoah, nice! Thank you very much. I noticed that the layout algorithm does not scale very well with the number of points. For instance, setting `n_points` to `200` in the example below makes the app crash (for me).

```r
library(shiny)
library(scatterD3)

n_points = 60
my_labs = as.character(lapply(1:n_points,function(x) paste(sample(letters,15),collapse='')))

ui = shinyUI(
  fluidPage(
    scatterD3Output('scatterd3')
  )
)
server = shinyServer(function(input, output, session) {
  output$scatterd3 = renderScatterD3({
    scatterD3(x=rnorm(n_points), y=rnorm(n_points), lab=my_labs,labels_positions="auto") 
  })
})
shinyApp(ui=ui, server=server)

```

**Comment by Tixierae** [comment]
I noticed another thing: when `transitions=TRUE`, it seems the layout algorithm is only called at initialization time (when the scatterD3 is first plotted). Then, when updating the plot, the label positions don't seem to be re-computed. It appears quite clearly in the reproducible example below:

```r
library(shiny)
library(scatterD3)

ui = shinyUI(
  fluidPage(
    selectInput("n_points",NULL,choices = 30:60,selected=30),
    scatterD3Output('scatterd3')
  )
)
server = shinyServer(function(input, output, session) {
  output$scatterd3 = renderScatterD3({
    my_labs = as.character(lapply(input$n_points,function(x) paste(sample(letters,15),collapse='')))
    scatterD3(x=rnorm(input$n_points), y=rnorm(input$n_points), lab=my_labs,labels_positions="auto",transitions=TRUE) 
  })
})
shinyApp(ui=ui, server=server)

```

**Comment by juba** [comment]
Thanks for taking the time to report these issues and provide reproducible examples. It is very useful and I really appreciate your efforts.

After battling with the "zoom on point" issue (and not totally fixing it), I'm in the middle of a quite big code refactoring, as it has become a bit of a mess. I'll take time on these issues once it is finished (hoping it won't introduce too many other problems).

Thanks again.

**Comment by Tixierae** [comment]
You're very welcome. Thank you very much for the update, and for this amazing widget!

**Comment by juba** [comment]
The automatic labels placement should now work with transitions. Positions are now recomputed after a transition if the option is set.

I'm still not completely satisfied with this implementation, though : labels placement is not optimal, I think the labeling algorithm needs a bit of work. So please consider this option has experimental.

One improvement I made though is that now, when a label is far from its point, a line is drawn between the two.

**Comment by juba** [comment]
Ah, and the performance issues are still there. I think I should automatically disable the option when the number of points is too high. Maybe the best should be to compute the positions by R instead of JavaScript, but this poses other issues.

**Comment by juba** [comment]
Ok, so I tweaked the labeler script a little. It's not perfect, but a bit better. I think I'll keep it like this for the moment.

**Comment by Tixierae** [comment]
Thank you very much, and apologies for the late answer, I've been crazy busy last week. It works very well now. I agree that the most sensible thing to do is disabling the option until a less complex algorithm comes out.

**Comment by juba** [comment]
No problem ! Thanks for all your feedback until now. I've not disabled automatic label placement for now, but I've reduced the number of sweeps in the algorithm. But it should still cause problems with several thousands of points.

Thanks again.

**Comment by Tixierae** [comment]
Indeed, it's a little bit better in terms of computation time now. In practice, when the labels are very long (as in my first repro example above), it seems to work fine for up to ~100 points - which is ok in most cases. When there are more points, we can automatically set `labels_positions = NULL`.

**Comment by juba** [comment]
I just pushed a commit which disables automatic labels positioning when there is more than 500 non-empty labels. It is still manageable on my laptop, even if it takes several seconds to compute.
