### ISSUE TITLE
Disable zoom with mouse wheel.

### ISSUE THREAD

**Issue by romanhaa** [juba/scatterD3#74]
Is it possible to disable zooming with the mouse wheel? Otherwise it can happen that you scroll through the Shiny page until the cursor ends up on the scatterD3 output and starts zooming.

Thanks 👍

**Comment by juba** [comment]
I just added a `disable_wheel` argument to `scatterD3` in the development version. This should disable zooming with mousewheel (but you can still pan and zomm by double clicking). For example :  

```r
scatterD3(x = mtcars$wt, y = mtcars$mpg, col_var = mtcars$cyl, disable_wheel = TRUE)
```
