### ISSUE TITLE
Change color scale.

### ISSUE THREAD

**Issue by romanhaa** [juba/scatterD3#75]
I think it would be great to be able to change the color scale. Currently the viridis scale is used which is not that great when you have a lot of points at the low end of the scale because the dark dots will dominate the plot. I'll see if I can figure it out myself.

**Comment by juba** [comment]
I just added the possibility to specify an interpolating function name as `colors` argument when the color variable is continuous. The default value is `"interpolateViridis"` but you can pass any existing d3-scale-chromatic interpolating function, for example :  

```r
scatterD3(x = mtcars$wt, y = mtcars$mpg, col_var = mtcars$qsec, colors = "interpolatePurples")
```

A list of interpolating function can be found here : 

https://github.com/d3/d3-scale-chromatic#sequential-single-hue
