### ISSUE TITLE
LDAvis clash

### ISSUE THREAD

**Issue by Tixierae** [juba/scatterD3#77]
Just a minor thing: when scatterD3 is used with [LDAvis](https://github.com/cpsievert/LDAvis) (`install.packages("LDAvis")`), the symbols disappear from the legend (they still show fine in the plot). In the reproducible example below, commenting out `visOutput('ldavis')` makes the symbols re-appear in the legend.
I'm comparing [ldavis.js](https://github.com/cpsievert/LDAvis/blob/master/inst/htmljs/ldavis.js) to [scatterD3-legend.js](https://github.com/juba/scatterD3/blob/master/inst/htmlwidgets/scatterD3-legend.js) to see if there is any variable conflict.

```r
library(shiny)
library(LDAvis)
library(scatterD3)

myjson = readChar('https://www.dropbox.com/s/xnraaj2vfn4dnkf/ldavis.json?dl=1', nchars=206627)
mtcars$names = rownames(mtcars)

ui = shinyUI(
  fluidPage(
    fluidRow(
      visOutput('ldavis'),
      br()
    ),
    fluidRow(
      scatterD3Output('scatterd3')
    )
  )
  )
server = shinyServer(function(input, output, session) {
  output$ldavis <- renderVis({
    myjson
  })
  output$scatterd3 = renderScatterD3({
    scatterD3(data = mtcars, x = wt, y = mpg, lab = names,
              col_var = cyl, symbol_var = am,
              xlab = "Weight", ylab = "Mpg", col_lab = "Cylinders",
              symbol_lab = "Manual transmission")
  })
})
shinyApp(ui=ui, server=server)
```

**Comment by Tixierae** [comment]
I compared [ldavis.js](https://github.com/cpsievert/LDAvis/blob/master/inst/htmljs/ldavis.js) to [scatterD3-legend.js](https://github.com/juba/scatterD3/blob/master/inst/htmlwidgets/scatterD3-legend.js), but couldn't identify any conflict. Do you have an idea where the problem could come from? Even if you don't have time to fix it, that would save me a lot of time, and maybe I could try to fix it myself :)

**Comment by juba** [comment]
Yep, that was not a JavaScript but a CSS conflict. LDAvis includes the following rule : 

```css
path {
   fill: none;
   stroke: none;
}
```

which will apply to all `path` SVG elements and remove their drawing and fill color. That's why symbols in legend are invisible.

A fix is to add a custom CSS rule in your shiny app, for example with this code in your UI definition : 

```r
    tags$style(HTML("
      .symbol-legend path {
        fill: #000000;
      }
    ")),
```

But it would be better for LDAvis not to include such a general CSS rule. Maybe you could open an issue there ?

**Comment by Tixierae** [comment]
Thanks for the very fast answer as always! I've filed an issue there: https://github.com/cpsievert/LDAvis/issues/96
