### ISSUE TITLE
Legend order for factor 

### ISSUE THREAD

**Issue by 1rdsk1** [juba/scatterD3#78]
Bug -  The guides says:

If your original R variable is a factor, its level orders should be preserved in the legend, both for symbols and colors.

mtcars$cyl_o <- factor(mtcars$cyl, levels=c("8", "6", "4"))
scatterD3(data = mtcars, x = wt, y = mpg, symbol_var = cyl_o)

Sure that works for symbols.
However, changing "symbol_var" to "col_var", fails to keep factor order:

scatterD3(data = mtcars, x = wt, y = mpg, col_var = cyl_o)

**Comment by juba** [comment]
It doesn't work in the CRAN version, but should work with the Github version.

Could you please install the development version and see if the problem disappears ?

Thanks !
