### ISSUE TITLE
Change the axis text to percentage format?

### ISSUE THREAD

**Issue by SPFL-Analysis** [juba/scatterD3#80]
Hello, is it possible to change the axis text to percentage format?

Thanks.
Graeme

**Comment by juba** [comment]
Not for the moment, but I may add a `tickFormat` argument to pass to underline `d3-scales` functions, if it could be useful.

**Comment by juba** [comment]
So you should be able to do it with the development version with the new `init_callback` argument.

Here is an example which formats the x axis as percentages :  

```r
scatterD3(data = mtcars, x = wt, y = mpg,
  init_callback = "function() {
    var scales = this.scales();
    var svg = this.svg();
    new_x_axis = scales.xAxis.tickFormat(d3v5.format(',.0%'));
    svg.select('.x.axis').call(new_x_axis);
  }"
)
```
