### ISSUE TITLE
Automatic label placement recomputes when adding point, changing color or showing ellipses

### ISSUE THREAD

**Issue by Tixierae** [juba/scatterD3#81]
Hi! The issue is that with the automatic label placement (great feature btw), the coordinates, which are expensive to get, are **recomputed every time (1) point color changes, (2) ellipses are toggled, or a (3) point is added/removed**. The issue does not happen when modifying label size or point opacity. Please find a minimal reproducible example below. Thank you in advance for any help!

```r
library(shiny)
library(scatterD3)

n_points = 120
my_labs = as.character(lapply(1:(n_points+1),function(x) paste(sample(letters,10),collapse='')))
my_labs_extra = tail(my_labs,1); my_labs = head(my_labs,-1)
my_x = rnorm(n_points); my_y = rnorm(n_points)
my_x_extra = c(my_x,rnorm(1)); my_y_extra = c(my_y,rnorm(1))
my_cols = c('#ff0000','#0000ff'); names(my_cols) = c('red','blue')

ui = shinyUI(
  fluidPage(
    checkboxInput('bool_el','show ellipses?'),
    checkboxInput('point','add/remove point?'),
    selectInput('color','point colors?',my_cols,'blue'),
    scatterD3Output('scatterd3')
  )
)
server = shinyServer(function(input, output, session) {
  output$scatterd3 = renderScatterD3({
    scatterD3(if(input$point){my_x_extra}else{my_x},if(input$point){my_y_extra}else{my_y},lab=if(input$point){my_labs_extra}else{my_labs},labels_positions='auto',transitions=TRUE,ellipses=input$bool_el,colors=input$color)
  })
})
shinyApp(ui=ui, server=server)
```
PS: Hi. I wasn't sure whether I should create a new issue or re-open [this one](https://github.com/juba/scatterD3/issues/73). I opted for the first option, hope this is fine.

**Comment by juba** [comment]
Yes, that's a known problem, unfortunately I don't have a workaround for now. Adding point, changing colors, etc. affect the plot scales and potentially its size (if a legend is displayed or not), so I'm forced to "reset" everything in theses cases. I know it's annoying for the labels placement...

**Comment by Tixierae** [comment]
Thank you for the quick reply! Pardon my ignorance, but would it be possible by any chance to expose the 'reset' parameter, to be used by users at their own risk, in certain cases? E.g., in my case, I don't need a legend, so if I could avoid recomputing the coordinates at least when changing colors or toggling ellipses, that would be a big improvement.

**Comment by juba** [comment]
No, that's more complicated than that unfortunately. But I'll take a look at it, as the current situation is far from optimal...

**Comment by Tixierae** [comment]
OK, thanks!

**Comment by juba** [comment]
Hi,

I'm well aware this issue is almost a year old, and you certainly forgot about it, but it should now be fixed in the development version.

Sorry for the delay, and thanks for taking the time to reporting it.

**Comment by Tixierae** [comment]
No problem, many thanks for addressing it! I will install the latest dev version and tell you if my problem is fixed!

**Comment by Tixierae** [comment]
Sorry for the very late update. I just checked, and it seems to work perfectly. Thank you!
