### ISSUE TITLE
Unexpected behavior of reset zoom

### ISSUE THREAD

**Issue by Tixierae** [juba/scatterD3#82]
Following up on the great feature that was added [here](https://github.com/juba/scatterD3/issues/76). **Procedure to reproduce the issue from the reproducible example below:**
* zoom on any point by using the dropdown
* click 'reset zoom'
* click 'change point opactiy' or 'change label size' -> the view is focused back on the point that had been previously zoomed on, even though the zoom has been reset

Of course, this issue can be solved by selecting 'None' in the dropdown. But when an item is still selected, would it be possible to remember that the zoom has been reset, and not repeat the zoom anytime the user updates the plot?

```r
library(shiny)
library(scatterD3)

mtcars$names = rownames(mtcars)

ui = shinyUI(
  fluidPage(
    fluidRow(
      selectInput("scatterD3_zoomon", "Zoom on :", choices = c("None", rownames(mtcars))),
      checkboxInput('opacity','change point opacity'),
      checkboxInput('size','change label size'),
      actionButton('scatterD3-reset-zoom','reset zoom?')
    ),
    fluidRow(
      scatterD3Output('scatterd3')
    )
  )
)
server = shinyServer(function(input, output, session) {
  
  output$scatterd3 = renderScatterD3({
    
    zoom_on <- if(input$scatterD3_zoomon=="None") {
      NULL 
    } else {
      as.numeric(mtcars[input$scatterD3_zoomon, c('wt','mpg')])
    }
    
    scatterD3(data=mtcars,x=wt,y=mpg,lab=names,
              zoom_on=zoom_on,zoom_on_level=8,
              point_opacity=if(input$opacity){0.5}else{0.9},labels_size=if(input$size){20}else{10},dom_id_reset_zoom='scatterD3-reset-zoom',
              transitions=TRUE)
  })
})
shinyApp(ui=ui, server=server)
```

**Comment by juba** [comment]
Yes, you're right, there's a conflict here : the "zoom on" dropdown and the "reset zoom" button. The first one should be set to "None" automatically when the zoom is reset, unfortunately there's no simple way for `scatterD3` to do this, as it doesn't know anything about the dropdown (or other) control. So if both features have to be present in an app, you should manage this yourself in JavaScript, I fear.

In your example, changing `ui` to something like this seems to work : 

```r
ui = shinyUI(
  fluidPage(
    fluidRow(
      selectInput("scatterD3_zoomon", "Zoom on :", choices = c("None", rownames(mtcars))),
      checkboxInput('opacity','change point opacity'),
      checkboxInput('size','change label size'),
      actionButton('scatterD3-reset-zoom','reset zoom?')
    ),
    fluidRow(
      scatterD3Output('scatterd3')
    ),
    tags$script(HTML(
      "
      var reset = document.getElementById('scatterD3-reset-zoom');
      var zoom = document.getElementById('scatterD3_zoomon');
      reset.addEventListener('click', event => {
        zoom.selectize.setValue('None');
      });
      "
    ))
  )
)
```

**Comment by Tixierae** [comment]
Awesome, thanks for the great fix! I had written some sort of a hack in R, but your approach is more elegant.
