### ISSUE TITLE
Any way to rotate axes?

### ISSUE THREAD

**Issue by daattali** [juba/scatterD3#84]
I don't have high expectations for this, but wanted to ask anyway. Is there any way to rotate the plot so that the axes on an angle, rather than X being left-right and Y being up-down?

**Comment by juba** [comment]
You mean you'd like the axes not to be orthogonal ? Or just change their orientation ?

**Comment by daattali** [comment]
Keep the orthogonality, just rotate the plane

**Comment by daattali** [comment]
Actually it's specifically for the CA plots made by explor, which I just noticed is also your package

**Comment by daattali** [comment]
It's totally ok if you say it's not possible!

**Comment by juba** [comment]
I took a quick look at it, it is not impossible but it causes strange side effects, and there many cases to take into account : categorical scales, axes position, etc. So I fear that I won't be able to implement it, unless there really is a very important use case.

**Comment by daattali** [comment]
Thanks for looking into it!
