### ISSUE TITLE
Save static webpage

### ISSUE THREAD

**Issue by dagewa** [juba/scatterD3#85]
Hi, I'd like to use `scatterD3` to generate a webpage that I will then copy to a server that doesn't have R. When I call `scatter3D` interactively I get `index.html` and a `lib/` directory, which is what I need, but this is written under `/tmp` and is deleted as soon as the R session exits. What I'd really like to do is generate the page within a script that is run non-interactively with `Rscript`. Is there a way to save to a user-specified directory instead?

**Comment by juba** [comment]
Is there a reason why you don't use Rmarkdown for this ?

**Comment by dagewa** [comment]
No reason other than a lack of awareness. It looks interesting, I'll see if I can figure out what to do.

**Comment by juba** [comment]
Yes, if you want to generate HTML (and other formats) from R code, you should definitely look into it. It also takes care of HTML widgets (like scatterD3) integration, and much much more.

**Comment by dagewa** [comment]
Thanks for the tip! I've got what I want now and it was quite straightforward (I just had to link to `pandoc` as described in https://rmarkdown.rstudio.com/docs/articles/pandoc.html to generate the html by `Rscript`).

I guess `rmarkdown` etc. are familiar to many current R users, but I wonder if a note in the documentation would be useful, for anyone else like me who discovers `scatterD3` first?

**Comment by juba** [comment]
Yes, you're right, I could drop a note to let users know of this possibility.

I reopen this issue so I don't forget. Thanks for the suggestion !
