### ISSUE TITLE
Updating caption in plot within shiny app

### ISSUE THREAD

**Issue by damirpolat** [juba/scatterD3#86]
I'm making a Shiny app that shows an interactive plot. The plot contains a title and text that need to change as users select `a` or `b` with `selectInput`.

Here's an example:

```
library(shiny)
library(scatterD3)

ui = fluidPage(
  fluidRow(
    column(2,
           selectInput("choose", "Choose", choices = c("a", "b"))
    ), 
    column(7, offset = 0, scatterD3Output("plot"))
  )
)

server = function(input, output) {
  choosing = reactive(input$choose)

  plot.text = reactive({
    if(choosing() == "a") {
      paste("Title for a ")
    } else if (choosing() == "b") {
      paste("Title for b ")
    }
  })

  title = reactive(
    if(choosing() == "a") {
      paste("Text for ", input$choose)
    } else if (choosing() == "b") {
      paste("Text for ", input$choose)
    }
  )

  output$plot = renderScatterD3({
    scatterD3(data = mtcars, x = mpg, y = disp,
              point_size = 100, point_opacity = 0.5,
              hover_size = 3, hover_opacity = 1,
              color = "purple",
              caption = list(text = plot.text(),
                             title = title()),
              transitions = TRUE)
  })
}

shinyApp(ui = ui, server = server)
```

The plot title and text don't change when I select either of the choices from the input control.

When `transitions = FALSE`, the plot is working, but I was wondering if there is a way to still change caption with transitions turned on.

Looking at the source code, most variables except for caption are updated in JavaScript code. It might be as simple as calling `caption_create()`, but I don't know JavaScript do actually implement this.

**Comment by juba** [comment]
Hi,

You're right, caption was not updated correctly. This should now be fixed in the development version, please let me know if the problem still occurs.

Thanks for taking the time to report the problem with a full reproducible example !

**Comment by damirpolat** [comment]
Great, it's all working now. Thanks!
