### ISSUE TITLE
Categorical axes not sorted alphabetically

### ISSUE THREAD

**Issue by sharvarinarendra** [juba/scatterD3#87]
Hi! I was wondering if there was a way to use the categorical variables in a particular order, without the plot sorting it alphabetically. Thank you!

**Comment by juba** [comment]
Hi,

This was not possible until now but I just pushed a small update to the development version which should now take into account levels order if a variable is a factor.

Thanks for the suggestion, and let me know if this still doesn't work !

**Comment by sharvarinarendra** [comment]
Hi Julien,

Thank you so much for the update, that is really helpful!

Best,
Sharvari
