### ISSUE TITLE
Can you have a background image to the plot?

### ISSUE THREAD

**Issue by sheikhbarabas** [juba/scatterD3#89]
Just wondering if you can set a background image to the scatterplot?

**Comment by juba** [comment]
Not really, as SVG elements don't allow a `background-image` rule, so you would have to manually insert an `<image>` tag in the generated SVG.

One possible thing could be to add a background image to the parent `<div>` via CSS, but this is only possible in an Rmarkdown document or Shiny app, and it will not strictly be limited to the chart. Something like this : 

```html
<style>
.scatterD3 {
  background-image: url(https://images.unsplash.com/photo-1547185942-2b5661136b1b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80);
}
.viewport {
  fill: transparent !important;
}
</style>
```
