### ISSUE TITLE
Speed up interactive features

### ISSUE THREAD

**Issue by neuro30** [juba/scatterD3#91]
Is there a way to optimize or speed up sctaterD3 when including large numbers of points (i.e. >10,000). I notice it becomes very choppy with zoom and lasso with my large dataset. Thanks

**Comment by juba** [comment]
You're right, as graphs are rendered as SVG, performance becomes quite bad past a few thousands of points. Unfortunately there is nothing I can really do about it, to speed up rendering another renderer should be used such as canvas or openGL, but the same interactions would not be possible. So `scatterD3` is limited for small datasets.

For big datasets while keeping some interactions you may take a look at `echarts4r` : https://echarts4r.john-coene.com/
